
services: 
  dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./site:/app
    environment:
      - ENV=development

