
services:

  portfolio:
    image: ghcr.io/nocapcbas/portfolio:prod
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.portfolio.rule=Host(`${HOST_DOMAIN}`)"
      # - "traefik.http.routers.portfolio.entrypoints=websecure"
      # - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      # - "traefik.http.services.portfolio.loadbalancer.server.port=${INTERNAL_PORT}"
      # watchtower label
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - shared

networks:
  shared:
    external: true
