# Use the official Golang image as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy go mod file
COPY ./site .

# Download all dependencies
RUN npm install

# Build the application
RUN npm run build

# Add debug commands
# RUN ls -la
# RUN ls -la dist/
# RUN ls -la dist/server/

CMD ["node", "./dist/server/entry.mjs"]