
services: 
  prod-local:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ENV=production
    restart: always
