# Use the official Golang image as the base image
FROM golang:1.20-alpine

# Set the working directory
WORKDIR /app

# Install Air for live reloading
RUN go install github.com/cosmtrek/air@latest

# Copy go mod and sum files
COPY go.mod ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Run the application using Air for live reloading
CMD ["air", "-c", ".air.toml"]
