version: '3.7'

services: 
  portfolio_app_backend:
    container_name: portfolio_app_backend
    build: 
      context: backend
    image: portfolio_app_backend
    ports: 
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/backend:cached

  portfolio_caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: portfolio_caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - portfolio_app_backend
