# Generated by Django 4.2.6 on 2024-06-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2500)),
                ('svg_icon_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('app_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('skills', models.ManyToManyField(to='core.skill')),
            ],
        ),
    ]
