# Generated by Django 4.1.7 on 2023-09-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(default='placeholder.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.skill'),
        ),
    ]
