# Generated by Django 4.1.7 on 2023-09-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_contact_project_repo_link_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
        migrations.DeleteModel(
            name='AppPictures',
        ),
    ]
