# Generated by Django 4.1.7 on 2024-03-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_skills_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
