# Generated by Django 4.1.7 on 2024-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_app_video_alter_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
