# Generated by Django 4.1.7 on 2024-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill_svg_icon_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
